FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["TuristeiRV.API/TuristeiRV.API.csproj", "TuristeiRV.API/"]
RUN dotnet restore "TuristeiRV.API/TuristeiRV.API.csproj"
COPY . .
WORKDIR "/src/TuristeiRV.API"
RUN dotnet build "TuristeiRV.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TuristeiRV.API.csproj" -c Release -o /app/out --verbosity detailed

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TuristeiRV.API.dll"]