FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src


COPY TuristeiRV.API.csproj ./TuristeiRV.API/

# COPY ./credentials/turisteirv.json /app/credentials/turisteirv.json

WORKDIR /src/TuristeiRV.API
RUN dotnet restore

COPY . .
RUN dotnet build -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app

# RUN mkdir -p /app/credentials
# RUN echo $GOOGLE_CREDENTIALS_BASE64 | base64 -d > /app/credentials/turisteirv.json

COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TuristeiRV.API.dll"]
